In [2]:
import numpy as np
house_size = [250,300,400,220,150,85,90,110,65,40]
rooms = ["childroom","bathroom","livingroom","guestroom","gameroom","woorkroom","kitchen","wc","dressingroom","balcony"]
price = [10000,50000,60000,80000,40000,10000,2500,1500,12500,16000]

house  = np.array([house_size,rooms, price])
print(house)

[['250' '300' '400' '220' '150' '85' '90' '110' '65' '40']
 ['childroom' 'bathroom' 'livingroom' 'guestroom' 'gameroom' 'woorkroom'
  'kitchen' 'wc' 'dressingroom' 'balcony']
 ['10000' '50000' '60000' '80000' '40000' '10000' '2500' '1500' '12500'
  '16000']]


In [4]:
house_size2 = house.T
print(house_size2)

[['250' 'childroom' '10000']
 ['300' 'bathroom' '50000']
 ['400' 'livingroom' '60000']
 ['220' 'guestroom' '80000']
 ['150' 'gameroom' '40000']
 ['85' 'woorkroom' '10000']
 ['90' 'kitchen' '2500']
 ['110' 'wc' '1500']
 ['65' 'dressingroom' '12500']
 ['40' 'balcony' '16000']]


In [16]:
import numpy as np
house.shape # 3 rows, 10 columns

(3, 10)

In [69]:
import numpy as np 
s = int(input("rows: "))
t = int(input("column: "))
mat = np.ones((s,t))
for p in range(0,s):
    for r in range(0,t):
        if (p%2 == 1 and r%2==1):
            mat[p][r]=0
print(mat)

rows: 6
column: 5
[[1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]]
